---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sigillum-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - get
- apiGroups:
  - sigillum.dev
  resources:
  - clustermailbackends
  - mailbackends
  - mailcredentials
  - mailpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sigillum.dev
  resources:
  - clustermailbackends/finalizers
  - mailbackends/finalizers
  verbs:
  - update
- apiGroups:
  - sigillum.dev
  resources:
  - clustermailbackends/status
  - mailbackends/status
  - mailcredentials/status
  - mailpolicies/status
  verbs:
  - get
  - patch
  - update
